name: 'Pure Checkout'
description: 'Clones repository using system git. Includes LFS and Submodules.'
inputs:
  token:
    description: 'Gitea/GitHub token'
    required: false
    default: ${{ github.token }}
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history.'
    required: false
    default: '1'

runs:
  using: "composite"
  steps:
    - name: Install Git and Git-LFS (Alpine)
      shell: sh
      run: |
        if command -v git >/dev/null 2>&1 && command -v git-lfs >/dev/null 2>&1; then
          echo "Git and Git-LFS are already installed. Skipping setup."
          exit 0
        fi
        
        echo "Dependencies missing. Detecting OS..."

        if command -v apk >/dev/null 2>&1; then
          apk add --no-cache git git-lfs openssh-client ca-certificates
        elif command -v apt-get >/dev/null 2>&1; then
          apt-get update
          apt-get install -y --no-install-recommends git git-lfs ca-certificates openssh-client
        fi  

    - name: Checkout Logic
      shell: sh
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_DEPTH: ${{ inputs.fetch-depth }}
      run: |
        git config --global --add safe.directory '*'
        git lfs install

        REPO_URL="${{ github.server_url }}/${{ github.repository }}.git"
        AUTH_URL=$(echo "$REPO_URL" | sed "s|https://|https://git:$INPUT_TOKEN@|")

        if [ ! -d ".git" ]; then
          echo "Cloning repository..."
          if [ "$INPUT_DEPTH" = "0" ]; then
             git clone "$AUTH_URL" .
          else
             git clone --depth "$INPUT_DEPTH" --reference ${{ github.sha }} "$AUTH_URL" .
          fi
        else
          echo "Repo exists, fetching..."
          git remote set-url origin "$AUTH_URL"
          git fetch origin --prune --prune-tags --force
        fi

        echo "Checking out ${{ github.sha }}..."
        git checkout -f ${{ github.sha }}

        echo "Updating submodules..."
        git submodule sync --recursive
        git submodule update --init --recursive

        echo "Pulling LFS objects..."
        git lfs pull
